### ISSUE TITLE
sidekick: better handling of sharepoint "share" links

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#706] opened 2021-02-19 23:36 UTC
there seems to a be a range of sharepoint "share" links that yield a "not found" if a preview is attempted directly on the URL. 
to reproduce:
(1) create a "share" link of a document in sharepoint
(2) paste it into the browser location bar
(3) try to hit "preview" in the sidekick
(4) this is the result

<img width="742" alt="Screen Shot 2021-02-19 at 3 36 01 PM" src="https://user-images.githubusercontent.com/5289336/108572892-2da8e080-72c8-11eb-9d36-76882f236611.png">

**Comment by rofe** [comment] 2021-02-28 10:49
@tripodsan this should possibly be addressed in `helix-content-proxy`

**Comment by tripodsan** [comment] 2021-03-01 08:42
@davidnuescheler I'm unable to reproduce the problem....

**Comment by rofe** [comment] 2021-03-02 10:11
@tripodsan I am able to reproduce it. You need to select a docx in sharepoint, then click "share" in the toolbar, enter your email address and click "copy link". You will end up with something like (fake site, doc ID and email):
```
https://adobe.sharepoint.com/:w:/s/MySite/MRPB1SXq5LdAgdmaaUmi0ysB3-QlpDodAlYRImkfUy0bog?email=my%40email.com&e=FrlUUa
```
Clicking the sidekick preview button from there will request 
```
https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@2.7.0?owner=adobe&repo=theblog&ref=master&path=%2F&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Aw%3A%2Fs%2FMySite%2FMRPB1SXq5LdAgdmaaUmi0ysB3-QlpDodAlYRImkfUy0bog%3Femail%3Dmy%2540email.com%26e%3DFrlUUa
```
which says not found.

**Comment by tripodsan** [comment] 2021-03-02 11:54
ok, I try again tomorrow.

**Comment by tripodsan** [comment] 2021-03-04 07:52
should be fixed.

**Closed by tripodsan** 2021-03-04 07:52 UTC
Labels: bug
